version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - ./src:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - XDEBUG_MODE=off        # off | debug | profile | coverage
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis

  web:
    image: nginx:1.26-alpine
    ports:
      - "8091:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: oil_magnate
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel
      PMA_PASSWORD: secret
    ports:
      - "8092:80"
    depends_on:
      - mysql

volumes:
  dbdata:
  redisdata:
